### ISSUE TITLE
SIGSEGV in device_after_raid when ether_fd is -1 (uraid.c:982)

### ISSUE THREAD

**Issue by nbriggs** [Interlisp/medley#450]
```
Core was generated by `ldex -g 1440x900 -sc 1440x900 -m 256 -t Medley Interlisp /export/home/briggs/li'.
Program terminated with signal SIGSEGV, Segmentation fault.
#0  0x00043678 in device_after_raid () at ../src/uraid.c:982
982       FD_SET(ether_fd, &LispReadFds);
[Current thread is 2 (Thread 1 (LWP 1))]
(gdb) where
#0  0x00043678 in device_after_raid () at ../src/uraid.c:982
#1  0x0002f0c0 in error (cp=0x76528 <errormsg> "Segmentation Fault at address 0.\nPlease record the signal and code information\nand do a 'v' before trying anything else.") at ../src/common.c:121
#2  <signal handler called>
#3  copy_region (h=899, width=90, dst=0x30a002, src=0x2) at ../src/uraid.c:326
#4  uraid_commands () at ../src/uraid.c:781
#5  0x0002f094 in error (cp=0x1dd60 "URAID Called:") at ../src/common.c:115
#6  0x0003e158 in OP_subrcall (subr_no=<optimized out>, argnum=3) at ../src/subr.c:122
#7  0x00033194 in dispatch () at ../src/xc.c:653
#8  0x0004a9d0 in main (argc=<optimized out>, argv=0xffbff58c) at ../src/main.c:539
(gdb) print ether_fd
$1 = -1
(gdb) 
```

**Comment by nbriggs** [comment]
Closed by https://github.com/Interlisp/maiko/commit/c07618f55cb0cc302cd1febfd06a716c0acf7f22
